USE dolphins;

DROP TABLE IF EXISTS PrecinctNeighbors;
DROP TABLE IF EXISTS PrecinctDemographics;
DROP TABLE IF EXISTS DistrictPrecincts;
DROP TABLE IF EXISTS Precincts;
DROP TABLE IF EXISTS Districts;
ALTER TABLE States
DROP FOREIGN KEY FK_CanonicalDistricting;
DROP TABLE IF EXISTS Districtings;
DROP TABLE IF EXISTS BoxWhiskers;
DROP TABLE IF EXISTS Jobs;
DROP TABLE IF EXISTS Counties;
DROP TABLE IF EXISTS States;

DROP TABLE IF EXISTS JobIdSequence;
DROP TABLE IF EXISTS DistrictingIdSequence;
DROP TABLE IF EXISTS DistrictIdSequence;
DROP TABLE IF EXISTS BoxWhiskerIdSequence;